version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: checknet_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

  backend:
    build: ./backend
    environment:
      PORT: 5000
      DATABASE_URL: postgres://postgres:postgres@db:5432/checknet_db
      OPENAI_API_KEY:
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - app-network
    command: npm run dev

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app-network
    command: npm start

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
